#ifndef TYPES_H
#define TYPES_H

#define LEON_UNSIGNED_CHAR '\0'
#define LEON_CHAR '\1'
#define LEON_UNSIGNED_SHORT '\2'
#define LEON_SHORT '\3'
#define LEON_UNSIGNED_INT '\4'
#define LEON_INT '\5'
#define LEON_FLOAT '\6'
#define LEON_DOUBLE '\7'
#define LEON_LONG '\36'
#define LEON_ARRAY '\200'
#define LEON_OBJECT '\11'
#define LEON_STRING '\20'
#define LEON_TRUE '\40'
#define LEON_FALSE '\41'
#define LEON_BOOLEAN '\40'
#define LEON_NULL '@'
#define LEON_UNDEFINED '\24'
#define LEON_DATE '\25'
#define LEON_BUFFER '\26'
#define LEON_REGEXP '\27'
#define LEON_NAN '\30'
#define LEON_NATIVE_OBJECT '\33'
#define LEON_INDIRECT '\34'
#define LEON_CONSTANT '\35'
#define LEON_INFINITY '\31'
#define LEON_MINUS_INFINITY '\32'
#define LEON_DYNAMIC '\335'
#define LEON_EMPTY '\377'

#define LEON_USE_INDEXING '\1'

#endif
